"""Add campaign detail fields

Revision ID: 907adae9264e
Revises: 
Create Date: 2024-12-31 18:52:32.459246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907adae9264e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('news_links', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('impact', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('impact')
        batch_op.drop_column('news_links')
        batch_op.drop_column('background')

    # ### end Alembic commands ###
